development:
  adapter: mysql
  database: spotus_development
  host: mysql.sundip.runnable.io
  username: root
  password:

test:
  adapter: mysql
  database: spotus_test
  host: mysql.sundip.runnable.io
  username: root
  password:

