development:
  adapter: mysql
  database: spotus_development
  host: "<%= ENV['DB_USER']%>"
  username: root
  password:

test:
  adapter: mysql
  database: spotus_test
  host: "<%= ENV['DB_USER']%>"
  username: root
  password:

